# Generated by Django 2.0.2 on 2018-02-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='article',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='article',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.IntegerField(default=0),
        ),
    ]
