# Generated by Django 2.0.2 on 2018-02-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180215_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='article',
        ),
        migrations.RemoveField(
            model_name='company',
            name='article',
        ),
    ]
